<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name = "base_length" value ="0.8"/>
<xacro:property name = "base_width" value ="0.4"/>
<xacro:property name = "base_height" value ="0.2"/>
<xacro:property name = "wheel_radius" value ="0.15"/>
<xacro:property name = "wheel_length" value ="0.06"/>




<link name ="base_footprint"/>
    <link name ="base_link">
        <visual>
            <geometry>
                <box size = "${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy ="0 0 0"/>
            <material name ="robot_color"/>
        </visual>
        <collision>
            <geometry>
                <box size = "${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy ="0 0 0"/>
        </collision>
        <xacro:box_inertia m="5.0" x="${base_length}"
                    y="${base_width}" z="${base_height}"
                    o_xyz ="0 0 ${base_height / 2.0}" o_rpy="0 0 0"
                    />
    </link>

       <link name ="load">
        <visual>
            <geometry>
                <box size = "${base_length/2} ${base_width/2} ${base_height/2}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy ="0 0 0"/>
            <material name ="grey"/>
        </visual>
        <collision>
            <geometry>
                <box size = "${base_length/2} ${base_width/2} ${base_height/2}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy ="0 0 0"/>
        </collision>
        <xacro:box_inertia m="5.0" x="${base_length/2.0}"
                    y="${base_width/2.0}" z="${base_height/2.0}"
                    o_xyz ="0 0 ${base_height/2.0}" o_rpy="0 0 0"
                    />
    </link>


    <link name ="front_sphare">
        <visual>
            <geometry>
            <sphere radius ="${wheel_radius /2.0}"/>
            </geometry>
            <origin xyz ="0 0 0" rpy ="0 0 0"/>
            <material name ="grey"/>
        </visual>

    <collision>
        <geometry>
            <sphere radius = "${wheel_radius /2.0}"/>
        </geometry>
        <origin xyz ="0 0 0" rpy ="0 0 0" />
    </collision>

        <xacro:caster_inertia m="0.5" r ="${wheel_radius /2.0}"
        o_xyz ="0 0 0" o_rpy ="0 0 0" />
    </link>

<xacro:macro name ="robot_wheels" params="prefix" >
    <link name ="${prefix}_wheel_link">
        <visual >
        <geometry>
            <cylinder radius ="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <origin xyz ="0 0 0" rpy ="${pi / 2.0} 0 0" />
        <material name ="grey"/>
        </visual>

    <collision>
        <geometry>
            <sphere radius ="${wheel_radius}"/>
        </geometry>
        <origin xyz ="0 0 0" rpy ="0 0 0" />
    </collision>

    <xacro:wheel_inertia m="1.0" h="${wheel_length}" r="${wheel_radius}" 
    o_xyz="0 0 0" o_rpy ="${pi / 2.0} 0 0" />
    </link>
</xacro:macro>

    <xacro:robot_wheels  prefix ="right"/>

    <xacro:robot_wheels prefix ="left"/>



    <joint type ="fixed" name ="base_foot_link">
        <parent link ="base_footprint"/>
        <child link ="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy ="0 0 0"/>

    </joint>


    <joint type ="fixed" name ="base_load_link">
        <parent link ="base_link"/>
        <child link ="load"/>
        <origin xyz="0 0 ${wheel_radius}" rpy ="0 0 0"/>

    </joint>
    <joint name = "base_front_sphare_link" type ="continuous">
        <parent link ="base_link"/>
        <child link="front_sphare"/>
        <origin xyz="${base_length / 3.0}  0  ${-wheel_length}" rpy ="0 0 0"/>
        <axis xyz ="0 1 0"/>
    </joint>

    <joint name ="base_right_wheel_joint" type ="continuous">
        <parent link ="base_link"/>
        <child link ="right_wheel_link"/>
        <origin xyz="${-base_length / 4.0} -0.225 0" rpy ="0 0 0"/>
        <axis xyz ="0 1 0"/>
    </joint>

     <joint name ="base_left_wheel_joint"  type ="continuous">
        <parent link ="base_link"/>
        <child link ="left_wheel_link"/>
        <origin xyz="${-base_length / 4.0}  0.225 0" rpy ="0 0 0"/>
        <axis xyz ="0 1 0"/>
    </joint>

</robot>